/**
 * Registry of well-known AI providers. Each preset knows its API protocol, endpoint, auth
 * header and a few suggested models, so the user only pastes an API key and picks a model.
 * Shared by the settings UI (browser) and the director (server) — no Node imports here.
 */

export type Protocol = "anthropic" | "openai" | "gemini";
export type ProviderGroup = "Popular" | "Fast inference" | "Open models" | "Gateways" | "Regional" | "Local" | "Other";

export interface ProviderPreset {
  id: string;
  name: string;
  group: ProviderGroup;
  protocol: Protocol;
  /** OpenAI-compatible base URL (…/v1); requests go to `${baseUrl}/chat/completions`. */
  baseUrl?: string;
  /** The user must supply the base URL (Azure resource, custom server). */
  needsBaseUrl?: boolean;
  baseUrlHint?: string;
  /** Header carrying the key: `Authorization: Bearer <key>` unless set (Azure uses `api-key`). */
  authHeader?: "bearer" | "api-key";
  keyOptional?: boolean;
  keyHint: string;
  keyUrl?: string;
  /** Recognise a pasted key: its prefix. */
  keyPrefix?: RegExp;
  /** Suggested models (the field accepts any model name). */
  models: string[];
  /** Whether the suggested models accept images (website screenshots). */
  vision: boolean;
  note?: string;
}

export const PROVIDER_PRESETS: ProviderPreset[] = [
  // ── Popular
  {
    id: "anthropic",
    name: "Anthropic Claude",
    group: "Popular",
    protocol: "anthropic",
    keyHint: "sk-ant-…",
    keyUrl: "https://console.anthropic.com/settings/keys",
    keyPrefix: /^sk-ant-/,
    models: ["claude-opus-5", "claude-sonnet-5", "claude-haiku-4-5"],
    vision: true,
  },
  {
    id: "openai",
    name: "OpenAI",
    group: "Popular",
    protocol: "openai",
    baseUrl: "https://api.openai.com/v1",
    keyHint: "sk-…",
    keyUrl: "https://platform.openai.com/api-keys",
    keyPrefix: /^sk-(proj-|svcacct-)?(?!ant-|or-)[A-Za-z0-9]/,
    models: ["gpt-4.1", "gpt-4o", "gpt-4.1-mini"],
    vision: true,
  },
  {
    id: "gemini",
    name: "Google Gemini",
    group: "Popular",
    protocol: "gemini",
    keyHint: "AIza…",
    keyUrl: "https://aistudio.google.com/apikey",
    keyPrefix: /^AIza/,
    models: ["gemini-2.5-flash", "gemini-2.5-pro"],
    vision: true,
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    group: "Popular",
    protocol: "openai",
    baseUrl: "https://openrouter.ai/api/v1",
    keyHint: "sk-or-…",
    keyUrl: "https://openrouter.ai/keys",
    keyPrefix: /^sk-or-/,
    models: ["anthropic/claude-sonnet-5", "openai/gpt-4.1", "google/gemini-2.5-flash", "meta-llama/llama-3.3-70b-instruct"],
    vision: true,
    note: "One key for hundreds of models from every lab.",
  },
  {
    id: "xai",
    name: "xAI Grok",
    group: "Popular",
    protocol: "openai",
    baseUrl: "https://api.x.ai/v1",
    keyHint: "xai-…",
    keyUrl: "https://console.x.ai",
    keyPrefix: /^xai-/,
    models: ["grok-4", "grok-3-mini"],
    vision: true,
  },
  {
    id: "mistral",
    name: "Mistral AI",
    group: "Popular",
    protocol: "openai",
    baseUrl: "https://api.mistral.ai/v1",
    keyHint: "API key",
    keyUrl: "https://console.mistral.ai/api-keys",
    models: ["mistral-large-latest", "mistral-medium-latest", "pixtral-large-latest"],
    vision: true,
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    group: "Popular",
    protocol: "openai",
    baseUrl: "https://api.deepseek.com/v1",
    keyHint: "sk-…",
    keyUrl: "https://platform.deepseek.com/api_keys",
    models: ["deepseek-chat", "deepseek-reasoner"],
    vision: false,
  },
  // ── Fast inference
  {
    id: "groq",
    name: "Groq",
    group: "Fast inference",
    protocol: "openai",
    baseUrl: "https://api.groq.com/openai/v1",
    keyHint: "gsk_…",
    keyUrl: "https://console.groq.com/keys",
    keyPrefix: /^gsk_/,
    models: ["llama-3.3-70b-versatile", "openai/gpt-oss-120b", "meta-llama/llama-4-scout-17b-16e-instruct"],
    vision: false,
  },
  {
    id: "cerebras",
    name: "Cerebras",
    group: "Fast inference",
    protocol: "openai",
    baseUrl: "https://api.cerebras.ai/v1",
    keyHint: "csk-…",
    keyUrl: "https://cloud.cerebras.ai",
    keyPrefix: /^csk-/,
    models: ["llama-3.3-70b", "gpt-oss-120b", "qwen-3-32b"],
    vision: false,
  },
  {
    id: "sambanova",
    name: "SambaNova",
    group: "Fast inference",
    protocol: "openai",
    baseUrl: "https://api.sambanova.ai/v1",
    keyHint: "API key",
    keyUrl: "https://cloud.sambanova.ai/apis",
    models: ["Meta-Llama-3.3-70B-Instruct", "DeepSeek-V3-0324"],
    vision: false,
  },
  // ── Open models
  {
    id: "together",
    name: "Together AI",
    group: "Open models",
    protocol: "openai",
    baseUrl: "https://api.together.xyz/v1",
    keyHint: "API key",
    keyUrl: "https://api.together.ai/settings/api-keys",
    models: ["meta-llama/Llama-3.3-70B-Instruct-Turbo", "Qwen/Qwen2.5-72B-Instruct-Turbo", "deepseek-ai/DeepSeek-V3"],
    vision: false,
  },
  {
    id: "fireworks",
    name: "Fireworks AI",
    group: "Open models",
    protocol: "openai",
    baseUrl: "https://api.fireworks.ai/inference/v1",
    keyHint: "fw_…",
    keyUrl: "https://fireworks.ai/account/api-keys",
    keyPrefix: /^fw_/,
    models: ["accounts/fireworks/models/llama-v3p3-70b-instruct", "accounts/fireworks/models/deepseek-v3"],
    vision: false,
  },
  {
    id: "deepinfra",
    name: "DeepInfra",
    group: "Open models",
    protocol: "openai",
    baseUrl: "https://api.deepinfra.com/v1/openai",
    keyHint: "API key",
    keyUrl: "https://deepinfra.com/dash/api_keys",
    models: ["meta-llama/Llama-3.3-70B-Instruct", "deepseek-ai/DeepSeek-V3"],
    vision: false,
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    group: "Open models",
    protocol: "openai",
    baseUrl: "https://router.huggingface.co/v1",
    keyHint: "hf_…",
    keyUrl: "https://huggingface.co/settings/tokens",
    keyPrefix: /^hf_/,
    models: ["meta-llama/Llama-3.3-70B-Instruct", "Qwen/Qwen2.5-72B-Instruct"],
    vision: false,
  },
  {
    id: "nvidia",
    name: "NVIDIA NIM",
    group: "Open models",
    protocol: "openai",
    baseUrl: "https://integrate.api.nvidia.com/v1",
    keyHint: "nvapi-…",
    keyUrl: "https://build.nvidia.com",
    keyPrefix: /^nvapi-/,
    models: ["meta/llama-3.3-70b-instruct", "deepseek-ai/deepseek-r1"],
    vision: false,
  },
  {
    id: "perplexity",
    name: "Perplexity",
    group: "Open models",
    protocol: "openai",
    baseUrl: "https://api.perplexity.ai",
    keyHint: "pplx-…",
    keyUrl: "https://www.perplexity.ai/settings/api",
    keyPrefix: /^pplx-/,
    models: ["sonar-pro", "sonar"],
    vision: false,
  },
  // ── Regional
  {
    id: "qwen",
    name: "Alibaba Qwen",
    group: "Regional",
    protocol: "openai",
    baseUrl: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
    keyHint: "sk-…",
    keyUrl: "https://modelstudio.console.alibabacloud.com",
    models: ["qwen-max", "qwen-plus", "qwen-vl-max"],
    vision: true,
  },
  {
    id: "moonshot",
    name: "Moonshot Kimi",
    group: "Regional",
    protocol: "openai",
    baseUrl: "https://api.moonshot.ai/v1",
    keyHint: "sk-…",
    keyUrl: "https://platform.moonshot.ai/console/api-keys",
    models: ["kimi-k2-0711-preview", "moonshot-v1-32k"],
    vision: false,
  },
  {
    id: "zhipu",
    name: "Z.ai GLM",
    group: "Regional",
    protocol: "openai",
    baseUrl: "https://api.z.ai/api/paas/v4",
    keyHint: "API key",
    keyUrl: "https://z.ai/manage-apikey/apikey-list",
    models: ["glm-4.5", "glm-4.5-air"],
    vision: false,
  },
  {
    id: "cohere",
    name: "Cohere",
    group: "Popular",
    protocol: "openai",
    baseUrl: "https://api.cohere.ai/compatibility/v1",
    keyHint: "API key",
    keyUrl: "https://dashboard.cohere.com/api-keys",
    models: ["command-a-03-2025", "command-r-plus"],
    vision: false,
  },
  {
    id: "novita",
    name: "Novita AI",
    group: "Open models",
    protocol: "openai",
    baseUrl: "https://api.novita.ai/v3/openai",
    keyHint: "API key",
    keyUrl: "https://novita.ai/settings/key-management",
    models: ["meta-llama/llama-3.3-70b-instruct", "deepseek/deepseek-v3"],
    vision: false,
  },
  {
    id: "hyperbolic",
    name: "Hyperbolic",
    group: "Open models",
    protocol: "openai",
    baseUrl: "https://api.hyperbolic.xyz/v1",
    keyHint: "API key",
    keyUrl: "https://app.hyperbolic.xyz/settings",
    models: ["meta-llama/Llama-3.3-70B-Instruct", "deepseek-ai/DeepSeek-V3"],
    vision: false,
  },
  {
    id: "nebius",
    name: "Nebius AI Studio",
    group: "Open models",
    protocol: "openai",
    baseUrl: "https://api.studio.nebius.com/v1",
    keyHint: "API key",
    keyUrl: "https://studio.nebius.com",
    models: ["meta-llama/Llama-3.3-70B-Instruct", "Qwen/Qwen2.5-72B-Instruct"],
    vision: false,
  },
  {
    id: "featherless",
    name: "Featherless",
    group: "Open models",
    protocol: "openai",
    baseUrl: "https://api.featherless.ai/v1",
    keyHint: "API key",
    keyUrl: "https://featherless.ai/account/api-keys",
    models: ["meta-llama/Llama-3.3-70B-Instruct"],
    vision: false,
  },
  {
    id: "venice",
    name: "Venice AI",
    group: "Open models",
    protocol: "openai",
    baseUrl: "https://api.venice.ai/api/v1",
    keyHint: "API key",
    keyUrl: "https://venice.ai/settings/api",
    models: ["llama-3.3-70b", "qwen3-235b"],
    vision: false,
  },
  {
    id: "github",
    name: "GitHub Models",
    group: "Gateways",
    protocol: "openai",
    baseUrl: "https://models.github.ai/inference",
    keyHint: "ghp_… / github_pat_…",
    keyUrl: "https://github.com/settings/tokens",
    keyPrefix: /^(ghp_|github_pat_)/,
    models: ["openai/gpt-4.1", "openai/gpt-4.1-mini", "meta/Llama-3.3-70B-Instruct"],
    vision: true,
    note: "Free tier with a GitHub token (models:read permission).",
  },
  {
    id: "vercel",
    name: "Vercel AI Gateway",
    group: "Gateways",
    protocol: "openai",
    baseUrl: "https://ai-gateway.vercel.sh/v1",
    keyHint: "API key",
    keyUrl: "https://vercel.com/dashboard/ai-gateway",
    models: ["anthropic/claude-sonnet-5", "openai/gpt-4.1", "google/gemini-2.5-flash"],
    vision: true,
  },
  {
    id: "cloudflare",
    name: "Cloudflare Workers AI",
    group: "Gateways",
    protocol: "openai",
    needsBaseUrl: true,
    baseUrlHint: "https://api.cloudflare.com/client/v4/accounts/ACCOUNT_ID/ai/v1",
    keyHint: "API token",
    keyUrl: "https://dash.cloudflare.com/profile/api-tokens",
    models: ["@cf/meta/llama-3.3-70b-instruct-fp8-fast"],
    vision: false,
    note: "Replace ACCOUNT_ID in the URL with your Cloudflare account ID.",
  },
  {
    id: "scaleway",
    name: "Scaleway",
    group: "Regional",
    protocol: "openai",
    baseUrl: "https://api.scaleway.ai/v1",
    keyHint: "Secret key",
    keyUrl: "https://console.scaleway.com/iam/api-keys",
    models: ["llama-3.3-70b-instruct", "mistral-small-3.1-24b-instruct-2503"],
    vision: false,
  },
  {
    id: "siliconflow",
    name: "SiliconFlow",
    group: "Regional",
    protocol: "openai",
    baseUrl: "https://api.siliconflow.com/v1",
    keyHint: "sk-…",
    keyUrl: "https://cloud.siliconflow.com/account/ak",
    models: ["deepseek-ai/DeepSeek-V3", "Qwen/Qwen2.5-72B-Instruct"],
    vision: false,
  },
  {
    id: "minimax",
    name: "MiniMax",
    group: "Regional",
    protocol: "openai",
    baseUrl: "https://api.minimax.io/v1",
    keyHint: "API key",
    keyUrl: "https://www.minimax.io/platform",
    models: ["MiniMax-M1", "MiniMax-Text-01"],
    vision: false,
  },
  {
    id: "volcengine",
    name: "Volcengine Ark (Doubao)",
    group: "Regional",
    protocol: "openai",
    baseUrl: "https://ark.cn-beijing.volces.com/api/v3",
    keyHint: "API key",
    keyUrl: "https://console.volcengine.com/ark",
    models: ["doubao-seed-1-6-250615"],
    vision: false,
    note: "Model = your endpoint ID or model name.",
  },
  // ── Local (runs on your machine, no key)
  {
    id: "ollama",
    name: "Ollama (local)",
    group: "Local",
    protocol: "openai",
    baseUrl: "http://localhost:11434/v1",
    keyOptional: true,
    keyHint: "not needed",
    keyUrl: "https://ollama.com/download",
    models: ["llama3.1", "qwen2.5", "mistral"],
    vision: false,
    note: "Free and private: run `ollama pull llama3.1`, then pick it here.",
  },
  {
    id: "lmstudio",
    name: "LM Studio (local)",
    group: "Local",
    protocol: "openai",
    baseUrl: "http://localhost:1234/v1",
    keyOptional: true,
    keyHint: "not needed",
    keyUrl: "https://lmstudio.ai",
    models: ["local-model"],
    vision: false,
    note: "Start LM Studio's local server, then Load models.",
  },
  {
    id: "llamacpp",
    name: "llama.cpp server (local)",
    group: "Local",
    protocol: "openai",
    baseUrl: "http://localhost:8080/v1",
    keyOptional: true,
    keyHint: "not needed",
    keyUrl: "https://github.com/ggml-org/llama.cpp",
    models: ["local-model"],
    vision: false,
    note: "Run `llama-server -m model.gguf --port 8080`.",
  },
  {
    id: "jan",
    name: "Jan (local)",
    group: "Local",
    protocol: "openai",
    baseUrl: "http://localhost:1337/v1",
    keyOptional: true,
    keyHint: "not needed",
    keyUrl: "https://jan.ai",
    models: ["llama3.2-3b-instruct"],
    vision: false,
    note: "Enable Jan's Local API Server in Settings.",
  },
  {
    id: "vllm",
    name: "vLLM (local)",
    group: "Local",
    protocol: "openai",
    baseUrl: "http://localhost:8000/v1",
    keyOptional: true,
    keyHint: "not needed",
    keyUrl: "https://docs.vllm.ai",
    models: ["Qwen/Qwen2.5-7B-Instruct"],
    vision: false,
    note: "Run `vllm serve <model>`.",
  },
  {
    id: "textgen",
    name: "text-generation-webui (local)",
    group: "Local",
    protocol: "openai",
    baseUrl: "http://localhost:5000/v1",
    keyOptional: true,
    keyHint: "not needed",
    keyUrl: "https://github.com/oobabooga/text-generation-webui",
    models: ["local-model"],
    vision: false,
    note: "Start it with the --api flag.",
  },
  {
    id: "koboldcpp",
    name: "KoboldCpp (local)",
    group: "Local",
    protocol: "openai",
    baseUrl: "http://localhost:5001/v1",
    keyOptional: true,
    keyHint: "not needed",
    keyUrl: "https://github.com/LostRuins/koboldcpp",
    models: ["koboldcpp"],
    vision: false,
  },
  {
    id: "gpt4all",
    name: "GPT4All (local)",
    group: "Local",
    protocol: "openai",
    baseUrl: "http://localhost:4891/v1",
    keyOptional: true,
    keyHint: "not needed",
    keyUrl: "https://www.nomic.ai/gpt4all",
    models: ["Llama 3.2 3B Instruct"],
    vision: false,
    note: "Enable the Local API Server in GPT4All settings.",
  },
  // ── Other
  {
    id: "azure",
    name: "Azure OpenAI",
    group: "Other",
    protocol: "openai",
    needsBaseUrl: true,
    baseUrlHint: "https://YOUR-RESOURCE.openai.azure.com/openai/v1",
    authHeader: "api-key",
    keyHint: "Azure key",
    keyUrl: "https://portal.azure.com",
    models: ["gpt-4.1", "gpt-4o"],
    vision: true,
    note: "Model = your deployment name.",
  },
  {
    id: "custom",
    name: "Any OpenAI-compatible API",
    group: "Other",
    protocol: "openai",
    needsBaseUrl: true,
    baseUrlHint: "https://api.example.com/v1",
    keyOptional: true,
    keyHint: "API key (if required)",
    models: [],
    vision: true,
    note: "Works with any service exposing /v1/chat/completions.",
  },
];

export const PRESET_MAP: Record<string, ProviderPreset> = Object.fromEntries(PROVIDER_PRESETS.map((p) => [p.id, p]));
export const PROVIDER_GROUPS: ProviderGroup[] = ["Local", "Popular", "Fast inference", "Open models", "Gateways", "Regional", "Other"];

/** Guess the provider from a pasted API key (most specific prefixes first). */
export function detectProvider(key: string): ProviderPreset | null {
  const k = key.trim();
  if (!k) return null;
  const ordered = [...PROVIDER_PRESETS].filter((p) => p.keyPrefix).sort((a, b) => (a.id === "openai" ? 1 : b.id === "openai" ? -1 : 0));
  return ordered.find((p) => p.keyPrefix!.test(k)) ?? null;
}

/** Local model servers run on the user's own machine. */
export const isLocalProvider = (id: string) => PRESET_MAP[id]?.group === "Local";

/** True when the page itself is served from this machine (so the server can reach localhost). */
export function isLocalHost(hostname: string) {
  return /^(localhost|127\.\d+\.\d+\.\d+|\[?::1\]?|0\.0\.0\.0)$/.test(hostname) || hostname.endsWith(".local");
}
