import type { Palette, PaletteId } from "./types";

export const PALETTES: Record<PaletteId, Palette> = {
  cyber: {
    id: "cyber",
    name: "Cyber Neon",
    bg0: "#05030d",
    bg1: "#140a2e",
    primary: "#00f0ff",
    secondary: "#ff2bd6",
    accent: "#7c4dff",
    text: "#ffffff",
  },
  inferno: {
    id: "inferno",
    name: "Inferno",
    bg0: "#0a0302",
    bg1: "#2a0800",
    primary: "#ff5a1f",
    secondary: "#ffc93c",
    accent: "#ff1e3c",
    text: "#fff4e6",
  },
  cosmos: {
    id: "cosmos",
    name: "Cosmos",
    bg0: "#02030c",
    bg1: "#0c1240",
    primary: "#6c8cff",
    secondary: "#c16bff",
    accent: "#43e6ff",
    text: "#f2f4ff",
  },
  gold: {
    id: "gold",
    name: "Black Gold",
    bg0: "#050403",
    bg1: "#1a140a",
    primary: "#e8c273",
    secondary: "#fff1c9",
    accent: "#a8782d",
    text: "#fff8e8",
  },
  synthwave: {
    id: "synthwave",
    name: "Synthwave",
    bg0: "#0d0221",
    bg1: "#2b0b3f",
    primary: "#ff3cac",
    secondary: "#ffb347",
    accent: "#2de2e6",
    text: "#fff0fb",
  },
  aurora: {
    id: "aurora",
    name: "Aurora",
    bg0: "#010b0d",
    bg1: "#062a2a",
    primary: "#2effc0",
    secondary: "#6a5cff",
    accent: "#b6ff5c",
    text: "#effffa",
  },
  ice: {
    id: "ice",
    name: "Arctic",
    bg0: "#030712",
    bg1: "#0b1c3a",
    primary: "#5cc8ff",
    secondary: "#ffffff",
    accent: "#3a6bff",
    text: "#ffffff",
  },
  toxic: {
    id: "toxic",
    name: "Toxic",
    bg0: "#020502",
    bg1: "#0b1a07",
    primary: "#a6ff00",
    secondary: "#00ff9c",
    accent: "#f5ff3d",
    text: "#f4ffe6",
  },
  midnight: {
    id: "midnight",
    name: "Midnight",
    bg0: "#08090f",
    bg1: "#161a2e",
    primary: "#8b9cff",
    secondary: "#c4b5fd",
    accent: "#5eead4",
    text: "#f5f6ff",
  },
  paper: {
    id: "paper",
    name: "Paper (light)",
    bg0: "#f6f6f9",
    bg1: "#ffffff",
    primary: "#5b5bf6",
    secondary: "#e2479b",
    accent: "#0ea5b7",
    text: "#0d0d17",
    light: true,
  },
  sunset: {
    id: "sunset",
    name: "Sunset Pop",
    bg0: "#140816",
    bg1: "#35103a",
    primary: "#ff7a59",
    secondary: "#ffd23f",
    accent: "#ff3d9a",
    text: "#fff7f2",
  },
  ocean: {
    id: "ocean",
    name: "Ocean",
    bg0: "#03121c",
    bg1: "#07304a",
    primary: "#38bdf8",
    secondary: "#34d399",
    accent: "#a78bfa",
    text: "#effaff",
  },
  mono: {
    id: "mono",
    name: "Editorial",
    bg0: "#070707",
    bg1: "#1b1b1b",
    primary: "#ffffff",
    secondary: "#ff2d2d",
    accent: "#9a9a9a",
    text: "#ffffff",
  },
  pastel: {
    id: "pastel",
    name: "Pastel (light)",
    bg0: "#f3f0fb",
    bg1: "#ffffff",
    primary: "#7c5cff",
    secondary: "#ff6fb1",
    accent: "#2fd0c0",
    text: "#17132b",
    light: true,
  },
  enterprise: {
    id: "enterprise",
    name: "Enterprise Blue (light)",
    bg0: "#f4f7fb",
    bg1: "#ffffff",
    primary: "#1f6feb",
    secondary: "#0ea5e9",
    accent: "#16a34a",
    text: "#0b1b33",
    light: true,
  },
  terminal: {
    id: "terminal",
    name: "Terminal Green",
    bg0: "#030805",
    bg1: "#0a1a10",
    primary: "#39ff88",
    secondary: "#b6ffd0",
    accent: "#27d3ff",
    text: "#e6ffee",
  },
  brutal: {
    id: "brutal",
    name: "Brutalist Yellow (light)",
    bg0: "#ffd84d",
    bg1: "#fffaf0",
    primary: "#ff4d2e",
    secondary: "#2d5bff",
    accent: "#111111",
    text: "#0a0a0a",
    light: true,
  },
  cream: {
    id: "cream",
    name: "Cream Editorial (light)",
    bg0: "#f5efe3",
    bg1: "#fffaf1",
    primary: "#c2410c",
    secondary: "#9a3412",
    accent: "#0f766e",
    text: "#1c1917",
    light: true,
  },
  violet: {
    id: "violet",
    name: "AI Violet",
    bg0: "#0a0616",
    bg1: "#1c0f38",
    primary: "#a855f7",
    secondary: "#fb923c",
    accent: "#ec4899",
    text: "#fbf7ff",
  },
  volt: {
    id: "volt",
    name: "Volt (black & yellow)",
    bg0: "#0a0a0a",
    bg1: "#1a1a1a",
    primary: "#ffe600",
    secondary: "#fff7a8",
    accent: "#ff3b30",
    text: "#ffffff",
  },
  spatial: {
    id: "spatial",
    name: "Spatial Indigo",
    bg0: "#05061a",
    bg1: "#12153d",
    primary: "#5b8cff",
    secondary: "#9f7bff",
    accent: "#4de1ff",
    text: "#f3f5ff",
  },
  hud: {
    id: "hud",
    name: "HUD Cyan",
    bg0: "#020a12",
    bg1: "#06202e",
    primary: "#35e6ff",
    secondary: "#1b6f8a",
    accent: "#ffb938",
    text: "#e4fbff",
  },
  swiss: {
    id: "swiss",
    name: "Swiss White (light)",
    bg0: "#f4f4f2",
    bg1: "#ffffff",
    primary: "#e8261c",
    secondary: "#1a1a1a",
    accent: "#8a8a8a",
    text: "#0f0f0f",
    light: true,
  },
  clay: {
    id: "clay",
    name: "Clay Pastel (light)",
    bg0: "#f7ece6",
    bg1: "#fff8f4",
    primary: "#ff7a59",
    secondary: "#9b8cff",
    accent: "#4fc9a8",
    text: "#2b1d1a",
    light: true,
  },
  chrome: {
    id: "chrome",
    name: "Liquid Chrome",
    bg0: "#0b0c10",
    bg1: "#1c1e25",
    primary: "#c9ccff",
    secondary: "#8e95a8",
    accent: "#ff9ee6",
    text: "#f6f7fb",
  },
  holo: {
    id: "holo",
    name: "Holographic",
    bg0: "#0a0714",
    bg1: "#1b1230",
    primary: "#ff8adf",
    secondary: "#7af0ff",
    accent: "#c6ff8a",
    text: "#fdf9ff",
  },
  dither: {
    id: "dither",
    name: "Dither Lime",
    bg0: "#0b0f0a",
    bg1: "#172114",
    primary: "#c5ff4a",
    secondary: "#3d5a2a",
    accent: "#ffffff",
    text: "#effee0",
  },
};
