import type { Palette, PaletteId } from "./types";

export const PALETTES: Record<PaletteId, Palette> = {
  cyber: {
    id: "cyber",
    name: "Cyber Neon",
    bg0: "#05030d",
    bg1: "#140a2e",
    primary: "#00f0ff",
    secondary: "#ff2bd6",
    accent: "#7c4dff",
    text: "#ffffff",
  },
  inferno: {
    id: "inferno",
    name: "Inferno",
    bg0: "#0a0302",
    bg1: "#2a0800",
    primary: "#ff5a1f",
    secondary: "#ffc93c",
    accent: "#ff1e3c",
    text: "#fff4e6",
  },
  cosmos: {
    id: "cosmos",
    name: "Cosmos",
    bg0: "#02030c",
    bg1: "#0c1240",
    primary: "#6c8cff",
    secondary: "#c16bff",
    accent: "#43e6ff",
    text: "#f2f4ff",
  },
  gold: {
    id: "gold",
    name: "Black Gold",
    bg0: "#050403",
    bg1: "#1a140a",
    primary: "#e8c273",
    secondary: "#fff1c9",
    accent: "#a8782d",
    text: "#fff8e8",
  },
  synthwave: {
    id: "synthwave",
    name: "Synthwave",
    bg0: "#0d0221",
    bg1: "#2b0b3f",
    primary: "#ff3cac",
    secondary: "#ffb347",
    accent: "#2de2e6",
    text: "#fff0fb",
  },
  aurora: {
    id: "aurora",
    name: "Aurora",
    bg0: "#010b0d",
    bg1: "#062a2a",
    primary: "#2effc0",
    secondary: "#6a5cff",
    accent: "#b6ff5c",
    text: "#effffa",
  },
  ice: {
    id: "ice",
    name: "Arctic",
    bg0: "#030712",
    bg1: "#0b1c3a",
    primary: "#5cc8ff",
    secondary: "#ffffff",
    accent: "#3a6bff",
    text: "#ffffff",
  },
  toxic: {
    id: "toxic",
    name: "Toxic",
    bg0: "#020502",
    bg1: "#0b1a07",
    primary: "#a6ff00",
    secondary: "#00ff9c",
    accent: "#f5ff3d",
    text: "#f4ffe6",
  },
  midnight: {
    id: "midnight",
    name: "Midnight",
    bg0: "#08090f",
    bg1: "#161a2e",
    primary: "#8b9cff",
    secondary: "#c4b5fd",
    accent: "#5eead4",
    text: "#f5f6ff",
  },
  paper: {
    id: "paper",
    name: "Paper (light)",
    bg0: "#f6f6f9",
    bg1: "#ffffff",
    primary: "#5b5bf6",
    secondary: "#e2479b",
    accent: "#0ea5b7",
    text: "#0d0d17",
    light: true,
  },
  sunset: {
    id: "sunset",
    name: "Sunset Pop",
    bg0: "#140816",
    bg1: "#35103a",
    primary: "#ff7a59",
    secondary: "#ffd23f",
    accent: "#ff3d9a",
    text: "#fff7f2",
  },
  ocean: {
    id: "ocean",
    name: "Ocean",
    bg0: "#03121c",
    bg1: "#07304a",
    primary: "#38bdf8",
    secondary: "#34d399",
    accent: "#a78bfa",
    text: "#effaff",
  },
  mono: {
    id: "mono",
    name: "Editorial",
    bg0: "#070707",
    bg1: "#1b1b1b",
    primary: "#ffffff",
    secondary: "#ff2d2d",
    accent: "#9a9a9a",
    text: "#ffffff",
  },
};
