/**
 * Random intros: a brief on a random topic, written the way a customer writes one (what the
 * business is, its features or services, how it works, who it's for, the tone, the button, the
 * contact details), and worded so the director reaches for the slides that topic shows off best:
 * 3D devices for an app, 3D homes for a homebuilder, cartoon characters for a kids' app, a
 * services showcase for an agency. Each brief carries a tagline the video opens on, and most a style
 * that shows the topic off (liquid, 3D, sci-fi…). Topics are designed intros, not trailer cuts: a
 * random intro has no footage or photos to cut a trailer from.
 *
 * Every name and contact detail is made up: brands from word parts, websites and emails on the
 * reserved ".example" domain, and the placeholder phone number 123-456-7890, so the intro
 * doesn't point at a real business.
 */

type Topic = {
  /** Short label for the topic. */
  kind: string;
  /** How the brief asks for the video ("an intro video", "an epic game trailer"). */
  ask: string;
  /** Word parts for the made-up name: one from each list. */
  name: [string[], string[]];
  /** What it is, after its name ("an analytics app for product teams"). */
  pitch: string;
  /** "Features" or "Services": four of `items` are listed. */
  list: "Features" | "Services";
  items: string[];
  /** How it works, in three steps (optional). */
  steps?: string[];
  audience: string;
  tones: string[];
  ctas: string[];
  /** Opening lines, one is picked: short, vivid and claim-free (the video opens on it). */
  taglines: string[];
  /** The niche's colours (primary, secondary): warm browns and greens for a restaurant, red and yellow for pizza… */
  colors?: [string, string];
  /** Styles that show this topic off (one is picked); none leaves the studio's own pick. */
  looks?: string[];
  /** Which contact details the brief gives. */
  contact: ("web" | "email" | "phone")[];
  /** A local business names its town. */
  local?: boolean;
};

const TOPICS: Topic[] = [
  {
    kind: "Analytics app",
    taglines: ["See the story behind your clicks", "Your data, finally talking back", "Less guessing, more knowing"],
    looks: ["keynote", "spatial", "horizon", "liquid"],
    ask: "a launch video",
    name: [["Lumen", "Cobalt", "Vela", "Prism", "Orbit"], ["metrics", "board", "scope", "pulse"]],
    pitch: "an analytics app for product teams",
    list: "Features",
    items: ["live dashboards", "AI insights", "cohort funnels", "team sharing", "custom reports", "alerts in Slack"],
    steps: ["connect your data", "build a dashboard", "share it with your team"],
    audience: "product managers and founders at growing startups",
    tones: ["modern and confident", "clean and premium"],
    ctas: ["Start free trial", "Book a demo"],
    contact: ["web", "email"],
  },
  {
    kind: "AI copilot",
    taglines: ["Write less boilerplate, ship more ideas", "Your codebase, now on speaking terms", "A pair programmer on your schedule"],
    looks: ["aiglow", "quantum", "holo", "wormhole"],
    ask: "a product intro",
    name: [["Nexa", "Vektor", "Synth", "Quill", "Atlas"], ["AI", "pilot", "mind", "assist"]],
    pitch: "an AI copilot for developers",
    list: "Features",
    items: ["code suggestions", "pull request reviews", "chat with your codebase", "test generation", "one-click deploys"],
    steps: ["install the extension", "open your project", "ask it anything"],
    audience: "software teams who ship every week",
    tones: ["futuristic and sleek", "dark with a glowing AI look"],
    ctas: ["Try it free", "Join the waitlist"],
    contact: ["web"],
  },
  {
    kind: "Homebuilder",
    colors: ["#a0522d", "#6b8f71"],
    taglines: ["Built for the way you live", "Your porch light is waiting", "Room to grow, a place to belong"],
    ask: "a homebuilder video",
    name: [["Harbor", "Maple", "Willow", "Cedar", "Stone"], [" Homes", " Ridge Homes", " Creek Builders", " Lane Homes"]],
    pitch: "building new homes in a walkable community with model homes and floor plans",
    list: "Features",
    items: ["an open-plan kitchen", "a spa bathroom", "a finished basement", "a bonus room", "a backyard with a pool", "a covered front porch"],
    steps: ["tour a model home", "choose your floor plan", "make it yours"],
    audience: "first-time buyers and growing households",
    tones: ["warm and welcoming", "elegant, golden hour"],
    ctas: ["Book a tour", "Schedule a visit"],
    contact: ["web", "phone"],
    local: true,
  },
  {
    kind: "Real estate agency",
    colors: ["#c9a227", "#3a5a80"],
    taglines: ["Find the door that feels like yours", "Keys, coffee and a new street", "Your next chapter starts at the curb"],
    looks: ["luxe", "editorial", "daybreak"],
    ask: "an agency intro",
    name: [["Keystone", "Bluebird", "Golden Gate", "Oak", "Ridgeline"], [" Realty", " Real Estate", " Properties"]],
    pitch: "a real estate agency helping buyers find a home in the community",
    list: "Services",
    items: ["homes for sale", "virtual tours", "neighbourhood guides", "first-time buyer help", "local agents", "home valuations"],
    steps: ["tell us what you need", "tour homes you love", "get the keys"],
    audience: "buyers and sellers in town",
    tones: ["trustworthy and warm", "polished and calm"],
    ctas: ["Find your home", "Talk to an agent"],
    contact: ["web", "phone", "email"],
    local: true,
  },
  {
    kind: "Kids learning app",
    colors: ["#ffbe0b", "#fb5607"],
    taglines: ["Learning that feels like recess", "Tiny minds, big adventures", "Count, read and giggle"],
    ask: "a cheerful cartoon intro",
    name: [["Bumble", "Tiny", "Sunny", "Giggle", "Pip"], ["learn", "words", "math", "ABC"]],
    pitch: "a learning app for kids with friendly characters",
    list: "Features",
    items: ["reading games", "counting songs", "stickers after lessons", "parent progress reports", "offline play"],
    steps: ["pick a world", "play a short lesson", "collect a sticker"],
    audience: "kids aged four to eight and their parents",
    tones: ["playful and bright", "soft and friendly"],
    ctas: ["Download the app", "Start learning"],
    contact: ["web"],
  },
  {
    kind: "Fitness app",
    colors: ["#ff006e", "#fb5607"],
    taglines: ["Your gym fits in your pocket", "Sweat now, brag later", "Small steps, loud results"],
    looks: ["liquid", "kinetic", "neon", "chrome"],
    ask: "an energetic launch video",
    name: [["Stride", "Pulse", "Flex", "Peak", "Motion"], ["fit", "coach", "go", "move"]],
    pitch: "a fitness app on your phone",
    list: "Features",
    items: ["guided workouts", "a step tracker", "meal plans", "streak badges", "a coach in your pocket"],
    steps: ["set your goal", "follow the plan", "watch your progress"],
    audience: "busy people who want to train at home",
    tones: ["bold and energetic", "fast and punchy"],
    ctas: ["Download the app", "Start free trial"],
    contact: ["web"],
  },



  {
    kind: "Coffee shop",
    colors: ["#6f4e37", "#c8a27a"],
    taglines: ["Slow mornings, strong coffee", "Your cup is ready when you are", "Brewed by neighbours, for neighbours"],
    looks: ["ink", "bloom", "paper"],
    ask: "a warm intro video",
    name: [["Bean", "Ember", "Copper", "Little"], [" & Co", " Roasters", " Coffee", " Café"]],
    pitch: "a neighbourhood coffee shop",
    list: "Features",
    items: ["single-origin espresso", "fresh pastries", "a cosy reading nook", "order ahead online", "a loyalty card"],
    steps: ["order ahead", "skip the line", "enjoy it warm"],
    audience: "locals and remote workers",
    tones: ["cosy and warm", "earthy and handmade"],
    ctas: ["Order ahead", "Visit us"],
    contact: ["web", "phone"],
    local: true,
  },


  {
    kind: "Developer platform",
    taglines: ["Push to deploy, then go to lunch", "From commit to live in one breath", "Ship on a Friday, sleep on Saturday"],
    looks: ["terminal", "datarain", "hud"],
    ask: "a developer platform launch",
    name: [["Ship", "Deploy", "Edge", "Stack"], ["yard", "kit", "base", "ops"]],
    pitch: "a platform that takes your code from commit to live",
    list: "Features",
    items: ["git push to deploy", "preview links", "edge functions", "live logs", "rollbacks"],
    steps: ["connect your repo", "push a commit", "share the preview link"],
    audience: "frontend teams",
    tones: ["technical and crisp", "dark terminal look"],
    ctas: ["Start building", "Deploy now"],
    contact: ["web"],
  },
  {
    kind: "Budget app",
    colors: ["#2a9d8f", "#e9c46a"],
    taglines: ["Know where your money goes", "Spend with a plan, not a sigh", "Payday, without the panic"],
    looks: ["flow", "bloom", "frosted"],
    ask: "a friendly product video",
    name: [["Penny", "Nest", "Coin", "Clover"], ["wise", "egg", "plan", "path"]],
    pitch: "a budgeting app for less time on spreadsheets and more time saving",
    list: "Features",
    items: ["spending by category", "savings goals", "bill reminders", "shared budgets", "bank sync"],
    steps: ["link your accounts", "set a goal", "watch your savings grow"],
    audience: "young couples saving together",
    tones: ["friendly and calm", "fresh and clear"],
    ctas: ["Download the app", "Get started"],
    contact: ["web", "email"],
  },
  {
    kind: "Travel app",
    colors: ["#00b4d8", "#ffb703"],
    taglines: ["Pack light, plan less, wander more", "Your next trip, sorted in a swipe", "Find the place that finds you"],
    looks: ["daybreak", "horizon", "aurora"],
    ask: "a travel app launch",
    name: [["Wander", "Roam", "Atlas", "Compass"], ["ly", "trip", "go", "way"]],
    pitch: "a trip planner for friends who travel together",
    list: "Features",
    items: ["trip planning on a map", "offline guides", "local food picks", "shared itineraries", "flight alerts"],
    steps: ["pick a destination", "plan it together", "go"],
    audience: "friends planning trips abroad",
    tones: ["sunny and adventurous", "light and airy"],
    ctas: ["Plan your trip", "Download the app"],
    contact: ["web"],
  },
  {
    kind: "Dental clinic",
    colors: ["#2ec4b6", "#4ea8de"],
    taglines: ["Smiles made comfortable", "Gentle care, bright smiles", "The friendliest chair in town"],
    looks: ["frosted", "enterprise", "bloom"],
    ask: "a welcoming intro",
    name: [["Bright", "Gentle", "Pearl", "Maple"], [" Dental", " Family Dental", " Dental Studio"]],
    pitch: "a family dental clinic",
    list: "Services",
    items: ["check-ups", "gentle care for kids", "whitening", "evening appointments", "a friendly team"],
    steps: ["book online", "meet your dentist", "leave smiling"],
    audience: "families in the neighbourhood",
    tones: ["calm and reassuring", "bright and clean"],
    ctas: ["Book a visit", "Book now"],
    contact: ["web", "phone"],
    local: true,
  },
  {
    kind: "Restaurant",
    colors: ["#8b5a2b", "#4f7942"],
    taglines: ["Pull up a chair, stay a while", "Made from scratch, served with heart", "Your table is set"],
    looks: ["ink", "luxe", "bloom"],
    ask: "a mouth-watering intro",
    name: [["Olive", "Saffron", "Basil", "Fig"], [" Kitchen", " Table", " & Vine", " House"]],
    pitch: "a Mediterranean restaurant",
    list: "Features",
    items: ["wood-fired flatbreads", "fresh mezze", "a sunny terrace", "weekend brunch", "takeaway"],
    audience: "foodies and friends",
    tones: ["warm and rustic", "sunny and fresh"],
    ctas: ["Book a table", "Order online"],
    contact: ["web", "phone"],
    local: true,
  },
  {
    kind: "Online course",
    colors: ["#7209b7", "#4cc9f0"],
    taglines: ["Learn it tonight, use it tomorrow", "Skills that fit your evenings", "Curious beats clueless"],
    looks: ["pop", "kinetic", "flow"],
    ask: "an explainer intro",
    name: [["Skill", "Learn", "Bright", "Mentor"], ["path", "lab", "class", "loop"]],
    pitch: "an online design course",
    list: "Features",
    items: ["video lessons", "real projects", "mentor feedback", "a community", "a certificate"],
    steps: ["enroll", "build real projects", "share your portfolio"],
    audience: "career changers learning UX and UI design",
    tones: ["inspiring and clear", "creative and colourful"],
    ctas: ["Start learning", "Enroll now"],
    contact: ["web", "email"],
  },
  {
    kind: "Delivery service",
    colors: ["#ff5400", "#ffd60a"],
    taglines: ["Ordered, picked up, at your door", "From our kitchen to your couch", "Dinner, minus the dishes"],
    looks: ["kinetic", "pop", "warp"],
    ask: "a product video",
    name: [["Swift", "Zip", "Dash", "Parcel"], ["post", "drop", "route", "box"]],
    pitch: "same-day local delivery for small shops",
    list: "Features",
    items: ["live tracking on a map", "same-day drop-offs", "proof of delivery", "a driver app", "simple pricing"],
    steps: ["book a pickup", "track it live", "get proof of delivery"],
    audience: "small shops and online sellers",
    tones: ["fast and efficient", "bold and clear"],
    ctas: ["Book a pickup", "Get started"],
    contact: ["web", "phone"],
  },
  {
    kind: "Law firm",
    colors: ["#b08d57", "#3a5a80"],
    taglines: ["Clear advice for complicated days", "Steady counsel, plain answers", "On your side of the table"],
    looks: ["swiss", "enterprise", "editorial"],
    ask: "a professional intro",
    name: [["Hartwell", "Ashford", "Kendall", "Whitmore"], [" & Partners", " Law", " Legal"]],
    pitch: "a law firm for small businesses",
    list: "Services",
    items: ["contracts", "business setup", "employment advice", "disputes", "trademarks"],
    steps: ["book a first call", "get a clear plan", "we handle the paperwork"],
    audience: "founders and small business owners",
    tones: ["calm, clean and professional", "trustworthy and minimal"],
    ctas: ["Book a consultation", "Get in touch"],
    contact: ["web", "phone", "email"],
    local: true,
  },
  {
    kind: "Pet care app",
    colors: ["#ff9f1c", "#2ec4b6"],
    taglines: ["Happy tails start here", "Walks, snacks and tummy rubs", "Your pet's favourite app"],
    ask: "a playful cartoon intro",
    name: [["Paw", "Woof", "Purr", "Fetch"], ["pal", "buddy", "care", "path"]],
    pitch: "a pet care app",
    list: "Features",
    items: ["walk booking", "vet reminders", "a pet profile", "trusted sitters", "photo updates"],
    steps: ["add your pet", "book a walk", "get photo updates"],
    audience: "busy pet owners",
    tones: ["playful and sunny", "cute and colourful"],
    ctas: ["Download the app", "Book a walk"],
    contact: ["web"],
  },
  {
    kind: "Construction company",
    colors: ["#f59e0b", "#64748b"],
    taglines: ["Built right, built to last", "Blueprints to keys, on schedule", "Strong foundations, honest work"],
    looks: ["slab", "enterprise", "mono"],
    ask: "a strong intro",
    name: [["Granite", "Iron", "Cornerstone", "Keystone"], [" Builders", " Construction", " Contracting"]],
    pitch: "a construction company",
    list: "Services",
    items: ["commercial builds", "renovations", "new builds", "site planning", "on-time handovers"],
    steps: ["tell us about the project", "get a clear quote", "we build it"],
    audience: "property owners and developers",
    tones: ["strong and dependable", "bold and industrial"],
    ctas: ["Get a quote", "Talk to our team"],
    contact: ["web", "phone"],
    local: true,
  },
  {
    kind: "Team chat app",
    taglines: ["Less email, more getting done", "Your team, in one room", "Talk less about work, do more of it"],
    looks: ["frosted", "clay", "liquid", "pop"],
    ask: "a SaaS launch video",
    name: [["Huddle", "Relay", "Chorus", "Thread"], ["ly", "hq", "up", "space"]],
    pitch: "a team chat app, instead of endless email threads",
    list: "Features",
    items: ["threaded channels", "video huddles", "shared docs", "integrations", "quick search"],
    steps: ["invite your team", "open a channel", "decide faster together"],
    audience: "remote teams",
    tones: ["bright and modern", "friendly and fast"],
    ctas: ["Start free trial", "Try it free"],
    contact: ["web"],
  },
  {
    kind: "Marketing agency",
    taglines: ["Brands people remember", "Loud ideas, sharp execution", "We make the scroll stop"],
    looks: ["brutalist", "editorial", "kinetic", "chrome"],
    ask: "an agency showreel intro",
    name: [["Bold", "North", "Spark", "Mint"], [" Studio", " & Co", " Creative", " Agency"]],
    pitch: "a creative agency for growing brands",
    list: "Services",
    items: ["brand identity", "web design", "social media", "video production", "SEO"],
    steps: ["discovery call", "strategy", "launch"],
    audience: "startups and growing brands",
    tones: ["bold and editorial", "creative and colourful"],
    ctas: ["Work with us", "Get in touch"],
    contact: ["web", "email"],
  },

  {
    kind: "Smart home app",
    colors: ["#4cc9f0", "#ffd166"],
    taglines: ["Your home, on speaking terms", "Lights, heat and locks in one tap", "Leave the house, take the controls"],
    looks: ["spatial", "holo", "frosted"],
    ask: "a sleek 3D launch video",
    name: [["Nest", "Haven", "Hearth", "Dwell", "Halo"], ["ly", "hub", "home", "sync"]],
    pitch: "a smart home app that runs your lights, heating and locks",
    list: "Features",
    items: ["one-tap scenes", "remote locks", "energy tracking", "voice control", "away mode"],
    steps: ["connect your devices", "set your scenes", "relax"],
    audience: "homeowners and renters",
    tones: ["sleek and futuristic", "calm and premium"],
    ctas: ["Download the app", "Get the app"],
    contact: ["web"],
  },
  {
    kind: "Cybersecurity platform",
    taglines: ["See threats before they see you", "Your network, under a watchful eye", "Calm on the surface, alert underneath"],
    looks: ["hud", "bridge", "datarain"],
    ask: "a mission-control style launch video",
    name: [["Sentry", "Bastion", "Aegis", "Vigil", "Ward"], ["ops", "grid", "shield", "core"]],
    pitch: "a security platform for IT teams",
    list: "Features",
    items: ["threat detection", "a live attack map", "zero-trust access", "automated alerts", "compliance reports"],
    steps: ["connect your cloud", "map your assets", "get alerts that matter"],
    audience: "IT and security teams",
    tones: ["dark, sci-fi and precise", "mission control"],
    ctas: ["Book a demo", "Talk to our team"],
    contact: ["web", "email"],
  },
  {
    kind: "EV charging app",
    colors: ["#00f5d4", "#3a86ff"],
    taglines: ["Charge up, roll on", "The road trip just got quieter", "Plug in, power up, drive on"],
    looks: ["warp", "chrome", "horizon"],
    ask: "a fast, futuristic launch video",
    name: [["Volt", "Amp", "Spark", "Current", "Ion"], ["way", "go", "path", "hub"]],
    pitch: "an app for finding and paying for EV chargers",
    list: "Features",
    items: ["a live charger map", "tap to pay", "route planning", "charging alerts", "trip history"],
    steps: ["find a charger", "plug in", "pay in the app"],
    audience: "electric car drivers",
    tones: ["electric and fast", "sleek and futuristic"],
    ctas: ["Download the app", "Find a charger"],
    contact: ["web"],
  },
  {
    kind: "Language app",
    colors: ["#06d6a0", "#ffd166"],
    taglines: ["Say it like a local", "Your passport to small talk", "Learn a language between coffees"],
    looks: ["pop", "kinetic", "bloom"],
    ask: "a bright, playful app intro",
    name: [["Lingo", "Hola", "Parla", "Bon", "Ciao"], ["loop", "pal", "ly", "buddy"]],
    pitch: "a language learning app with quick daily lessons",
    list: "Features",
    items: ["bite-size lessons", "speaking practice", "streaks and badges", "travel phrases", "chat with tutors"],
    steps: ["pick a language", "learn a few words a day", "start a conversation"],
    audience: "travellers and curious learners",
    tones: ["bright and playful", "colourful and upbeat"],
    ctas: ["Start learning", "Download the app"],
    contact: ["web"],
  },
  {
    kind: "Plant shop",
    colors: ["#2d6a4f", "#95d5b2"],
    taglines: ["Bring the outside in", "Green thumbs not required", "A little jungle for your windowsill"],
    looks: ["bloom", "daybreak", "ink"],
    ask: "a fresh, leafy intro",
    name: [["Fern", "Leaf", "Moss", "Sprout", "Ivy"], [" & Pot", " House", " Lane", " Co"]],
    pitch: "a neighbourhood plant shop",
    list: "Services",
    items: ["indoor plants", "potting workshops", "gift bundles", "a pot and soil bar", "rare finds"],
    steps: ["visit or order online", "pick your plant", "we help it thrive"],
    audience: "new plant parents and apartment dwellers",
    tones: ["fresh and green", "calm and natural"],
    ctas: ["Visit the shop", "Book a workshop"],
    contact: ["web", "phone"],
    local: true,
  },
  {
    kind: "Event ticketing app",
    colors: ["#f72585", "#4361ee"],
    taglines: ["Your night out, one tap away", "Doors open, phones ready", "Skip the queue, keep the vibe"],
    looks: ["neon", "horizon", "kinetic"],
    ask: "a neon launch video",
    name: [["Gig", "Encore", "Stage", "Velvet", "Backstage"], ["pass", "ly", "door", "go"]],
    pitch: "an app for finding live events and booking seats",
    list: "Features",
    items: ["mobile passes", "seat maps", "friends' plans", "event alerts", "easy transfers"],
    steps: ["find a show", "pick your seats", "scan in at the door"],
    audience: "music fans and night owls",
    tones: ["neon and electric", "loud and glowing"],
    ctas: ["Get the app", "Find a show"],
    contact: ["web"],
  },
  {
    kind: "Recipe app",
    colors: ["#e76f51", "#2a9d8f"],
    taglines: ["Dinner, figured out", "Cook tonight, smile tomorrow", "Your fridge has ideas"],
    looks: ["bloom", "pop", "clay"],
    ask: "a warm, colourful app intro",
    name: [["Basil", "Pepper", "Simmer", "Spoon", "Saffron"], ["ly", "box", "kit", "list"]],
    pitch: "a recipe app with weekly meal plans",
    list: "Features",
    items: ["weekly meal plans", "smart shopping lists", "step-by-step videos", "pantry search", "family favourites"],
    steps: ["pick your meals", "shop the list", "cook along"],
    audience: "busy home cooks",
    tones: ["warm and colourful", "fresh and friendly"],
    ctas: ["Download the app", "Start cooking"],
    contact: ["web"],
  },
  {
    kind: "Barber shop",
    colors: ["#b22234", "#3a5a80"],
    taglines: ["Fresh cuts, good conversation", "Your chair is waiting", "Clean lines, warm towels"],
    looks: ["luxe", "mono", "dither"],
    ask: "a sharp, confident intro",
    name: [["Sharp", "Classic", "Kings", "Fade", "Main Street"], [" Barbers", " Barber Co", " Cuts"]],
    pitch: "a neighbourhood barber shop",
    list: "Services",
    items: ["classic cuts", "skin fades", "beard trims", "hot towel shaves", "kids' cuts"],
    steps: ["book online", "take a seat", "walk out looking sharp"],
    audience: "men and boys who like a clean cut",
    tones: ["bold and classic", "vintage and confident"],
    ctas: ["Book a chair", "Book now"],
    contact: ["web", "phone"],
    local: true,
  },
  {
    kind: "Bakery",
    colors: ["#b5651d", "#f0b67f"],
    taglines: ["Warm from the oven, made by hand", "Good mornings start here", "Flour, butter and a little love"],
    looks: ["bloom", "paper", "daybreak"],
    ask: "a warm, cosy intro",
    name: [["Golden", "Rise", "Crumb", "Butter", "Honey"], [" Bakery", " Bakehouse", " & Crust"]],
    pitch: "a family bakery baking fresh each morning",
    list: "Services",
    items: ["fresh sourdough", "morning pastries", "custom cakes", "catering trays", "birthday cupcakes"],
    steps: ["order ahead", "pick it up warm", "share it at the table"],
    audience: "neighbours, families and early risers",
    tones: ["warm and homemade", "sweet and golden"],
    ctas: ["Order a cake", "Visit the bakery"],
    contact: ["web", "phone"],
    local: true,
  },
  {
    kind: "Pizza place",
    colors: ["#d62828", "#fcbf49"],
    taglines: ["Hot, cheesy and on its way", "Fresh dough, big flavour", "Slice into the weekend"],
    looks: ["pop", "kinetic", "clay"],
    ask: "a bold, mouth-watering intro",
    name: [["Tony's", "Brick", "Slice", "Fire", "Napoli"], [" Pizza", " Pizzeria", " Pie Co"]],
    pitch: "a wood-fired pizza place",
    list: "Features",
    items: ["wood-fired pizzas", "family deals", "online ordering", "vegan options", "late-night pickup"],
    steps: ["pick your pizza", "we fire it up", "grab a slice"],
    audience: "families and late-night cravings",
    tones: ["bold and fun", "warm and rustic"],
    ctas: ["Order now", "See the menu"],
    contact: ["web", "phone"],
    local: true,
  },
  {
    kind: "Hair salon",
    colors: ["#b76e79", "#7d5a7d"],
    taglines: ["Leave the chair feeling like you", "Your hair, your way", "Colour that turns heads"],
    looks: ["luxe", "editorial", "frosted"],
    ask: "an elegant salon intro",
    name: [["Glow", "Velvet", "Mane", "Luxe", "Willow"], [" Salon", " Hair Studio", " & Co"]],
    pitch: "a hair salon for cuts, colour and styling",
    list: "Services",
    items: ["cuts and blowouts", "balayage", "colour refresh", "bridal styling", "smoothing services"],
    steps: ["book your stylist", "relax in the chair", "walk out glowing"],
    audience: "anyone ready for a fresh look",
    tones: ["elegant and modern", "soft and glamorous"],
    ctas: ["Book an appointment", "Book now"],
    contact: ["web", "phone"],
    local: true,
  },
  {
    kind: "Nail salon",
    colors: ["#ff4d8d", "#b388ff"],
    taglines: ["Ten little works of art", "Gloss, polish, glow", "Your hands deserve a holiday"],
    looks: ["bloom", "pop", "chrome"],
    ask: "a glossy, colourful intro",
    name: [["Polish", "Gloss", "Petal", "Pink"], [" Nail Bar", " Nails", " Nail Studio"]],
    pitch: "a nail salon",
    list: "Services",
    items: ["manicures", "pedicures", "gel nails", "nail art", "group spa days"],
    steps: ["pick your colour", "sit back", "show off your hands"],
    audience: "friends, brides and busy professionals",
    tones: ["glossy and fun", "soft and pretty"],
    ctas: ["Book a visit", "Book now"],
    contact: ["web", "phone"],
    local: true,
  },
  {
    kind: "Auto repair shop",
    colors: ["#e85d04", "#9aa5b1"],
    taglines: ["Keys in, worries out", "We speak fluent engine", "Your car's favourite garage"],
    looks: ["slab", "mono", "enterprise"],
    ask: "a strong, trustworthy intro",
    name: [["Main Street", "Precision", "Ironside", "Rapid"], [" Auto", " Auto Care", " Garage"]],
    pitch: "an auto repair shop",
    list: "Services",
    items: ["oil changes", "brake repair", "tire rotation", "engine diagnostics", "state inspections"],
    steps: ["book a slot", "drop off your car", "drive away ready"],
    audience: "local drivers and families",
    tones: ["strong and dependable", "honest and friendly"],
    ctas: ["Book a service", "Get a quote"],
    contact: ["web", "phone"],
    local: true,
  },
  {
    kind: "Car wash",
    colors: ["#0077b6", "#00c2d1"],
    taglines: ["Shine on, drive on", "From muddy to gleaming", "Your car, showroom ready"],
    looks: ["kinetic", "chrome", "warp"],
    ask: "a fast, shiny intro",
    name: [["Splash", "Sparkle", "Blue Wave", "Shine"], [" Car Wash", " Auto Spa"]],
    pitch: "a car wash and detailing shop",
    list: "Services",
    items: ["express wash", "hand wax", "interior detailing", "monthly wash club", "tire shine"],
    steps: ["pull in", "relax for a few minutes", "drive off sparkling"],
    audience: "drivers who like a clean ride",
    tones: ["fast and glossy", "bright and bubbly"],
    ctas: ["Join the wash club", "Find us"],
    contact: ["web", "phone"],
    local: true,
  },
  {
    kind: "Plumber",
    colors: ["#0077b6", "#f4a261"],
    taglines: ["Drips fixed, days saved", "Leaks out, peace in", "The pipes are in good hands"],
    looks: ["enterprise", "flow", "mono"],
    ask: "a friendly, reliable intro",
    name: [["Reliable", "Blue Pipe", "Clearwater", "Ace"], [" Plumbing", " Plumbing Co", " Plumbers"]],
    pitch: "a local plumbing company",
    list: "Services",
    items: ["drain cleaning", "water heaters", "pipe repairs", "bathroom installs", "emergency call-outs"],
    steps: ["call or book online", "we come to you", "the job gets done right"],
    audience: "homeowners and landlords",
    tones: ["friendly and reliable", "clean and calm"],
    ctas: ["Call us", "Book a plumber"],
    contact: ["web", "phone"],
    local: true,
  },
  {
    kind: "Electrician",
    colors: ["#ffb703", "#219ebc"],
    taglines: ["Bright ideas, safely wired", "Power on, worries off", "Lights, switches and peace of mind"],
    looks: ["mono", "neon", "enterprise"],
    ask: "a bright, modern intro",
    name: [["Spark", "Volt", "Brightline", "Current"], [" Electric", " Electrical", " Electricians"]],
    pitch: "a licensed electrician",
    list: "Services",
    items: ["rewiring", "lighting installs", "panel upgrades", "EV charger installs", "ceiling fans"],
    steps: ["tell us the job", "get a clear quote", "switch it on"],
    audience: "homeowners and small businesses",
    tones: ["bright and modern", "clean and trustworthy"],
    ctas: ["Get a quote", "Call us"],
    contact: ["web", "phone"],
    local: true,
  },
  {
    kind: "Heating and cooling",
    colors: ["#e63946", "#48cae4"],
    taglines: ["Cool summers, cosy winters", "Your home at just the right temperature", "Heat on, chill out"],
    looks: ["frosted", "flow", "aurora"],
    ask: "a fresh, comfortable intro",
    name: [["Comfort", "Polar", "Northwind", "Cozy"], [" Heating & Air", " HVAC", " Climate Co"]],
    pitch: "a heating and air conditioning company",
    list: "Services",
    items: ["AC installs", "furnace repairs", "duct cleaning", "seasonal tune-ups", "smart thermostats"],
    steps: ["book a visit", "we check your system", "enjoy the comfort"],
    audience: "homeowners in hot summers and cold winters",
    tones: ["fresh and calm", "clean and friendly"],
    ctas: ["Book a tune-up", "Call us"],
    contact: ["web", "phone"],
    local: true,
  },
  {
    kind: "Landscaping",
    colors: ["#6a994e", "#a7c957"],
    taglines: ["Curb appeal, grown with care", "Green lawns, happy weekends", "Outside, made beautiful"],
    looks: ["daybreak", "bloom", "ink"],
    ask: "a fresh, green intro",
    name: [["Green", "Evergreen", "Oakleaf", "Meadow"], [" Landscaping", " Lawn Co", " Gardens"]],
    pitch: "a landscaping and lawn care company",
    list: "Services",
    items: ["lawn care", "garden design", "tree trimming", "patios and paths", "seasonal cleanups"],
    steps: ["walk the yard together", "plan the design", "enjoy the view"],
    audience: "homeowners who love their yard",
    tones: ["fresh and natural", "sunny and green"],
    ctas: ["Get a quote", "Book a visit"],
    contact: ["web", "phone"],
    local: true,
  },
  {
    kind: "Cleaning service",
    colors: ["#06d6a0", "#118ab2"],
    taglines: ["Come home to clean", "Sparkle without the scrubbing", "Your weekends, back"],
    looks: ["frosted", "clay", "flow"],
    ask: "a bright, fresh intro",
    name: [["Sparkle", "Tidy", "Fresh", "Spotless"], [" Cleaning", " Cleaners", " Home Care"]],
    pitch: "a home and office cleaning service",
    list: "Services",
    items: ["home cleaning", "deep cleans", "move-out cleans", "office cleaning", "recurring visits"],
    steps: ["book online", "we clean", "you relax"],
    audience: "busy families and small offices",
    tones: ["bright and fresh", "calm and tidy"],
    ctas: ["Book a clean", "Get a quote"],
    contact: ["web", "phone"],
    local: true,
  },
  {
    kind: "Florist",
    colors: ["#e56b6f", "#6a994e"],
    taglines: ["Say it with petals", "Fresh flowers, kind words", "Bouquets for big and small days"],
    looks: ["bloom", "ink", "editorial"],
    ask: "a soft, romantic intro",
    name: [["Petal", "Rose", "Poppy", "Blossom"], [" & Stem", " Flowers", " Florist"]],
    pitch: "a neighbourhood flower shop",
    list: "Services",
    items: ["fresh bouquets", "wedding flowers", "event flowers", "weekly subscriptions", "potted plants"],
    steps: ["choose a bouquet", "add a note", "we hand-tie it"],
    audience: "romantics, hosts and party planners",
    tones: ["soft and romantic", "fresh and colourful"],
    ctas: ["Order flowers", "Visit the shop"],
    contact: ["web", "phone"],
    local: true,
  },
  {
    kind: "Pet grooming",
    colors: ["#ff9f1c", "#2ec4b6"],
    taglines: ["Fluffy, fresh and fabulous", "Clean pups, happy owners", "Good dogs deserve a spa day"],
    looks: ["pop", "bloom", "clay"],
    ask: "a playful, colourful intro",
    name: [["Sudsy", "Fluffy", "Happy Paws", "Bubbles"], [" Grooming", " Pet Spa", " Dog Spa"]],
    pitch: "a dog and cat grooming salon",
    list: "Services",
    items: ["baths and blowouts", "nail trims", "breed cuts", "teeth brushing", "puppy first visits"],
    steps: ["book a visit", "drop off your pet", "pick up a fluffy friend"],
    audience: "dog and cat owners",
    tones: ["playful and sunny", "cute and colourful"],
    ctas: ["Book a groom", "Book now"],
    contact: ["web", "phone"],
    local: true,
  },
  {
    kind: "Daycare",
    colors: ["#ffbe0b", "#3a86ff"],
    taglines: ["Little hands, big discoveries", "Where play comes first", "Hugs, crayons and new friends"],
    looks: ["sunnypark", "storybook", "cartoon"],
    ask: "a cheerful cartoon intro",
    name: [["Little", "Sunny", "Tiny", "Busy Bee"], [" Sprouts", " Steps", " Learners"]],
    pitch: "a daycare and preschool",
    list: "Features",
    items: ["play-based learning", "outdoor time", "music and art", "home-style snacks", "parent updates"],
    steps: ["book a tour", "meet the teachers", "start the adventure"],
    audience: "parents of toddlers and preschoolers",
    tones: ["playful and warm", "bright and gentle"],
    ctas: ["Book a tour", "Visit us"],
    contact: ["web", "phone"],
    local: true,
  },
  {
    kind: "Yoga studio",
    colors: ["#9d8189", "#84a59d"],
    taglines: ["Breathe in, stretch out", "Find your flow", "A calm hour, just for you"],
    looks: ["aurora", "eclipse", "cosmic"],
    ask: "a calm, flowing intro",
    name: [["Lotus", "Still", "Sun", "Om"], [" Yoga", " Yoga Studio", " Flow"]],
    pitch: "a yoga studio",
    list: "Services",
    items: ["beginner classes", "hot yoga", "pilates", "meditation", "private sessions"],
    steps: ["pick a class", "roll out your mat", "leave lighter"],
    audience: "beginners and regulars",
    tones: ["calm and flowing", "soft and peaceful"],
    ctas: ["Book a class", "Try a class"],
    contact: ["web", "phone"],
    local: true,
  },
  {
    kind: "Boxing gym",
    colors: ["#d00000", "#ffba08"],
    taglines: ["Gloves on, doubts off", "Hit hard, train smart", "Your toughest hour of the day"],
    looks: ["kinetic", "brutalist", "neon"],
    ask: "a loud, high-energy intro",
    name: [["Iron", "Knockout", "Southpaw", "Titan"], [" Boxing", " Boxing Club", " Fight Gym"]],
    pitch: "a boxing and fitness gym",
    list: "Services",
    items: ["boxing classes", "strength training", "personal training", "open gym", "youth programs"],
    steps: ["book a trial class", "learn the basics", "train with the team"],
    audience: "beginners and fighters",
    tones: ["loud and gritty", "bold and fast"],
    ctas: ["Book a trial", "Join the gym"],
    contact: ["web", "phone"],
    local: true,
  },
  {
    kind: "Photography studio",
    colors: ["#c9a227", "#8d99ae"],
    taglines: ["Moments you'll want to keep", "Say cheese and mean it", "Your story, in focus"],
    looks: ["luxe", "editorial", "mono"],
    ask: "an elegant, cinematic intro",
    name: [["Golden Hour", "Lens", "Frame", "Shutter"], [" Studio", " Photography", " Photo Co"]],
    pitch: "a portrait and wedding photography studio",
    list: "Services",
    items: ["family portraits", "headshots", "weddings", "newborn shoots", "photo prints"],
    steps: ["book a session", "we plan the shots", "get your gallery"],
    audience: "families, couples and professionals",
    tones: ["elegant and cinematic", "warm and timeless"],
    ctas: ["Book a session", "See our work"],
    contact: ["web", "phone"],
    local: true,
  },
  {
    kind: "Tattoo studio",
    colors: ["#c1121f", "#adb5bd"],
    taglines: ["Ink with a story", "Your skin, your story", "Bold lines, steady hands"],
    looks: ["dither", "brutalist", "luxe"],
    ask: "a bold, edgy intro",
    name: [["Black", "Iron", "Needle", "Raven"], [" Ink", " Tattoo", " Tattoo Co"]],
    pitch: "a custom tattoo studio",
    list: "Services",
    items: ["custom designs", "fine line work", "cover-ups", "walk-ins", "aftercare advice"],
    steps: ["share your idea", "approve the design", "get inked"],
    audience: "first-timers and collectors",
    tones: ["bold and edgy", "dark and artistic"],
    ctas: ["Book a consult", "See our art"],
    contact: ["web", "phone"],
    local: true,
  },
  {
    kind: "Ice cream shop",
    colors: ["#ff8fab", "#7bdff2"],
    taglines: ["Life's short, get the sprinkles", "Scoops of happy", "Cones, cups and summer days"],
    looks: ["pop", "bloom", "clay"],
    ask: "a sweet, colourful intro",
    name: [["Scoop", "Sprinkle", "Sundae", "Swirl"], [" Shop", " Creamery", " & Co"]],
    pitch: "a small-batch ice cream shop",
    list: "Features",
    items: ["small-batch ice cream", "waffle cones", "sundaes", "milkshakes", "party tubs"],
    steps: ["pick a flavour", "add the toppings", "enjoy the sunshine"],
    audience: "families and sweet tooths",
    tones: ["sweet and colourful", "sunny and fun"],
    ctas: ["Visit us", "See the flavours"],
    contact: ["web", "phone"],
    local: true,
  },
  {
    kind: "Taco truck",
    colors: ["#e63946", "#43aa8b"],
    taglines: ["Tacos on the move", "Follow the truck, find the tacos", "Fresh tortillas, big flavour"],
    looks: ["pop", "kinetic", "comic"],
    ask: "a bold, fun intro",
    name: [["El", "Taco", "Salsa", "Verde"], [" Fuego", " Loco", " Rojo"]],
    pitch: "a taco truck",
    list: "Features",
    items: ["street tacos", "burritos", "daily specials", "catering", "late-night menu"],
    steps: ["find the truck", "order at the window", "eat while it's hot"],
    audience: "lunch crowds and late-night cravings",
    tones: ["bold and fun", "loud and colourful"],
    ctas: ["Find the truck", "See the menu"],
    contact: ["web", "phone"],
    local: true,
  },
  {
    kind: "Bookstore",
    colors: ["#7f5539", "#588157"],
    taglines: ["Lose yourself for an hour", "Pages, coffee and quiet corners", "Your next favourite book is here"],
    looks: ["editorial", "ink", "paper"],
    ask: "a cosy, literary intro",
    name: [["Chapter", "Dog-Ear", "Lantern", "Paper Moon"], [" Books", " Bookshop", " Book Co"]],
    pitch: "an independent bookstore",
    list: "Services",
    items: ["new releases", "used books", "book clubs", "kids' story time", "gift cards"],
    steps: ["browse the shelves", "ask for a pick", "take a story home"],
    audience: "readers of young and old",
    tones: ["cosy and literary", "warm and quiet"],
    ctas: ["Visit the shop", "Join the book club"],
    contact: ["web", "phone"],
    local: true,
  },
  {
    kind: "Moving company",
    colors: ["#f77f00", "#3a86ff"],
    taglines: ["Boxes in, smiles out", "Your move, handled with care", "Heavy lifting, light hearts"],
    looks: ["warp", "kinetic", "enterprise"],
    ask: "a fast, friendly intro",
    name: [["Swift", "Easy", "Big Blue", "Two Trucks"], [" Movers", " Moving", " Moving Co"]],
    pitch: "a local moving company",
    list: "Services",
    items: ["local moves", "long-distance moves", "packing help", "storage", "piano moving"],
    steps: ["get a quote", "we pack and load", "settle into your new place"],
    audience: "families and small offices on the move",
    tones: ["friendly and fast", "bold and reliable"],
    ctas: ["Get a quote", "Book a move"],
    contact: ["web", "phone"],
    local: true,
  },
  {
    kind: "Bed and breakfast",
    colors: ["#9c6644", "#6b9080"],
    taglines: ["Stay a night, leave rested", "Your home away from home", "Slow mornings, soft pillows"],
    looks: ["luxe", "daybreak", "editorial"],
    ask: "a warm, inviting intro",
    name: [["Willow", "Harbor", "Maple", "Rose"], [" Inn", " House", " B&B"]],
    pitch: "a bed and breakfast",
    list: "Features",
    items: ["cosy rooms", "homemade breakfast", "garden patio", "local tours", "pet-friendly stays"],
    steps: ["book your room", "check in", "wake up to breakfast"],
    audience: "couples and weekend travellers",
    tones: ["warm and inviting", "quiet and charming"],
    ctas: ["Book a stay", "See the rooms"],
    contact: ["web", "phone"],
    local: true,
  },
  {
    kind: "Tax preparer",
    colors: ["#1d4ed8", "#10b981"],
    taglines: ["Taxes, sorted", "Numbers in order, minds at ease", "Less paperwork, more weekend"],
    looks: ["swiss", "enterprise", "mono"],
    ask: "a clean, professional intro",
    name: [["Ledger", "Clearview", "Keystone", "Northstar"], [" Tax", " Tax & Books", " Accounting"]],
    pitch: "a tax and bookkeeping office",
    list: "Services",
    items: ["tax returns", "bookkeeping", "payroll", "small business advice", "IRS letter help"],
    steps: ["book a call", "send your papers", "we file on time"],
    audience: "families and small business owners",
    tones: ["calm and professional", "clean and trustworthy"],
    ctas: ["Book a call", "Get started"],
    contact: ["web", "phone"],
    local: true,
  },
  {
    kind: "Roofing company",
    colors: ["#9b2226", "#ee9b00"],
    taglines: ["A roof you can count on", "Rain or shine, covered", "Solid above, cosy below"],
    looks: ["slab", "enterprise", "mono"],
    ask: "a strong, dependable intro",
    name: [["Peak", "Crown", "Ridge", "Shield"], [" Roofing", " Roofers", " Roof Co"]],
    pitch: "a roofing company",
    list: "Services",
    items: ["roof repairs", "new roofs", "gutter cleaning", "storm damage help", "roof inspections"],
    steps: ["book an inspection", "get a clear quote", "we get to work"],
    audience: "homeowners and property managers",
    tones: ["strong and dependable", "bold and clear"],
    ctas: ["Get a quote", "Book an inspection"],
    contact: ["web", "phone"],
    local: true,
  },
  {
    kind: "Dance studio",
    colors: ["#f72585", "#7209b7"],
    taglines: ["Find your rhythm", "Step, spin, shine", "Dance like the room is yours"],
    looks: ["kinetic", "neon", "pop"],
    ask: "a lively, rhythmic intro",
    name: [["Rhythm", "Twirl", "Stage", "Pulse"], [" Dance", " Dance Studio", " Dance Co"]],
    pitch: "a dance studio for kids and adults",
    list: "Services",
    items: ["ballet", "hip hop", "tap", "adult classes", "spring recitals"],
    steps: ["pick a class", "try it out", "dance on stage"],
    audience: "kids, teens and adults",
    tones: ["lively and bright", "bold and rhythmic"],
    ctas: ["Book a trial class", "See the schedule"],
    contact: ["web", "phone"],
    local: true,
  },
];

const OPENERS = ["Make", "Create", "I need", "Can you make", "Please make"];
const TOWNS = ["Austin", "Denver", "Portland", "Raleigh", "Boise", "Nashville", "Tampa", "Madison"];

/**
 * A random intro idea: the topic, its brief and a style that shows it off (`look`, a template id,
 * or none to leave the studio's pick). `rand` is Math.random by default (pass a seeded one for
 * repeatable picks).
 */
/** A random intro: its topic, made-up name, tagline, the brief, and a style that shows it off. */
export type RandomIntro = { kind: string; name: string; tagline: string; prompt: string; look?: string; colors?: { primary: string; secondary: string } };

export function randomIntro(rand: () => number = Math.random, avoid?: string): RandomIntro {
  const pick = <T,>(xs: T[]) => xs[Math.floor(rand() * xs.length) % xs.length];
  // (Not the same topic twice in a row.)
  const pool = TOPICS.filter((t) => t.kind !== avoid);
  return brief(pick(pool.length ? pool : TOPICS), rand);
}

/** A brief on one topic (by its label), or undefined for an unknown topic. */
export function introFor(kind: string, rand: () => number = Math.random) {
  const t = TOPICS.find((x) => x.kind === kind);
  return t ? brief(t, rand) : undefined;
}

function brief(t: Topic, rand: () => number): RandomIntro {
  const pick = <T,>(xs: T[]) => xs[Math.floor(rand() * xs.length) % xs.length];
  const name = pick(t.name[0]) + pick(t.name[1]);
  const slug = name.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "");
  const items = [...t.items].sort(() => rand() - 0.5).slice(0, 4);
  const town = t.local ? pick(TOWNS) : undefined;
  // (A placeholder number, plainly not a real one.)
  const phone = "123-456-7890";
  const contact = [
    t.contact.includes("web") ? `Website: ${slug}.example` : "",
    t.contact.includes("email") ? `Email: hello@${slug}.example` : "",
    t.contact.includes("phone") ? `Phone: ${phone}` : "",
  ].filter(Boolean);
  const cta = pick(t.ctas);
  const tagline = pick(t.taglines);
  const lines = [
    `${pick(OPENERS)} ${t.ask} for "${name}", ${t.pitch}${town ? ` in ${town}` : ""}.`,
    `Tagline: "${tagline}"`,
    `${t.list}: ${items.join(", ")}.`,
    ...(t.steps ? [`How it works: ${t.steps.join(", ")}.`] : []),
    `Audience: ${t.audience}.`,
    `Tone: ${pick(t.tones)}.`,
    `End with ${/^[aeiou]/i.test(cta) ? "an" : "a"} "${cta}" button.`,
    `Contact: ${contact.join(" · ")}`,
    `Social: @${slug} on Instagram, Facebook and TikTok`,
    ...(/\bapp\b/.test(t.pitch) ? ["App: on the App Store and Google Play"] : []),
  ];
  const colors = t.colors ? { primary: t.colors[0], secondary: t.colors[1] } : undefined;
  return { kind: t.kind, name, tagline, prompt: lines.join("\n"), look: t.looks?.length ? pick(t.looks) : undefined, colors };
}

/** The styles that show a topic off (empty: the studio's own pick). */
export function looksOf(kind: string): string[] {
  return TOPICS.find((t) => t.kind === kind)?.looks ?? [];
}

/** The topics a random intro picks from. */
export const RANDOM_TOPICS = TOPICS.map((t) => t.kind);
