import type { Metadata } from "next";
import Link from "next/link";
import Nav, { Logo } from "@/components/Nav";
import notices from "./notices.json";

export const metadata: Metadata = {
  title: "Open-source licences · IntroMaker",
  description: "The open-source software IntroMaker is built on, and its licences.",
};

type Pkg = { name: string; version: string; licence: string; homepage?: string; note?: string; text?: string; notice?: string };

/** Third-party notices, generated by `npm run licenses` (see THIRD_PARTY_NOTICES.md). */
export default function Licenses() {
  const packages = notices.packages as Pkg[];
  const runtime = notices.runtime as Pkg[];
  return (
    <main>
      <Nav />
      <article className="legal">
        <h1>Open-source licences</h1>
        <p className="lead">
          IntroMaker is built on open-source software. Every component is open source and its licence allows commercial use. Their notices and licence
          texts are reproduced here, as those licences ask.
        </p>

        <h2>Licence conditions</h2>
        <ul>
          {Object.entries(notices.conditions as Record<string, string>).map(([l, w]) => (
            <li key={l}>
              <strong>{l}</strong>: {w}
            </li>
          ))}
        </ul>

        <h2>Loaded at runtime</h2>
        <ul>
          {runtime.map((p) => (
            <li key={p.name}>
              <a href={p.homepage} target="_blank" rel="noopener noreferrer">
                {p.name}
              </a>{" "}
              ({p.licence}): {p.note}
            </li>
          ))}
        </ul>

        <h2>Images and media</h2>
        <ul>
          {(notices.assets as { path: string; licence: string; source: string }[]).map((a) => (
            <li key={a.path}>
              <code>{a.path.replace(/^public\//, "/")}</code> ({a.licence}): {a.source}
            </li>
          ))}
        </ul>

        <h2>Packages ({packages.length})</h2>
        {packages.map((p) => (
          <details key={`${p.name}@${p.version}`} className="licence">
            <summary>
              {p.name} <span className="muted">{p.version}</span> · {p.licence}
            </summary>
            {p.homepage && (
              <p>
                <a href={p.homepage} target="_blank" rel="noopener noreferrer">
                  {p.homepage}
                </a>
              </p>
            )}
            {p.note && <p>{p.note}</p>}
            {p.notice && <pre>{p.notice}</pre>}
            {p.text && <pre>{p.text}</pre>}
          </details>
        ))}

        <p className="back">
          <Link href="/studio" className="btn btn-primary">
            Try for Free!
          </Link>
        </p>
      </article>
      <footer className="footer">
        <Logo />
        <span>
          © {new Date().getFullYear()} IntroMaker · <Link href="/privacy">Privacy</Link> · <Link href="/license">Licence</Link> · <Link href="/licenses">Open-source licences</Link>
        </span>
      </footer>
    </main>
  );
}
